// 常量
export const tabsName = ['商品', '待刊登', '刊登中', '刊登成功', '刊登失败'];
export const listingStatus = {
  商品: -1,
  待刊登: 0,
  刊登中: 3,
  刊登成功: 1,
  刊登失败: 2
};

// OA系统颜色	shien商城颜色	shenin自营颜色
export const colorMap = {
  black: ['黑色', '黑色'],
  blue: ['蓝色', '蓝色'],
  white: ['白色', '白色'],
  pink: ['粉色', '粉色'],
  red: ['红色', '红色'],
  green: ['绿色', '绿色'],
  grey: ['灰色', '灰色'],
  yellow: ['黄色', '黄色'],
  silver: ['银色', '银色'],
  purple: ['紫色', '紫色'],
  gold: ['金色', '金色'],
  orange: ['橙色', '橙色'],
  brown: ['棕色', '棕色'],
  beige: ['米色', '米色'],
  'rose red': ['玫红色', '玫红色'],
  coffee: ['咖啡棕', '咖啡色'],
  khaki: ['卡其色', '卡其色'],
  'rose gold': ['玫瑰金', '玫瑰金'],
  multicolor: ['多色', '多色'],
  'wine red': ['酒红色', '酒红色'],
  'dark blue': ['深色水洗蓝', 'Dark Blue'],
  'light blue': ['淡蓝色', 'Light Blue'],
  'navy blue': ['藏蓝色', '藏蓝色'],
  transparent: ['透明	', '透明'],
  gray: ['M104烟草灰', '焦糖色'],
  'sky blue': ['薄荷蓝', '薄荷蓝'],
  'dark grey': ['深灰色', '深灰色'],
  'dark green': ['墨绿色', '墨绿色'],
  'light green': ['M108春芽绿', 'Light Green'],
  'light grey': ['浅灰色', '浅灰色'],
  'light pink': ['浅粉色', '浅粉色'],
  navy: ['GE06 深海玫瑰', 'Navy'],
  'royal blue': ['宝蓝色', '宝蓝色'],
  nude: ['裸色', 'Taupe'],
  'army green': ['军绿色', '军绿色'],
  champagne: ['香槟色', '香槟色'],
  'light purple': ['紫罗兰色', 'Light Purple'],
  bronze: ['古铜色', '古铜色'],
  'warm white': ['月光白', '亮白'],
  apricot: ['杏色', '杏色'],
  'lake blue': ['雾霾蓝', '雾霾蓝'],
  'dark pink': ['珊瑚粉', '珊瑚粉'],
  'dark brown': ['巧克力棕', 'Dark Brown'],
  'light brown': ['摩卡棕', 'Light Brown'],
  'dark gray': ['#03灰棕色', '浅色水洗蓝'],
  rose: ['玫瑰红色', 'Rose'],
  camel: ['驼色', '驼色'],
  'black&white': ['黑白色', '黑白色'],
  'dark purple': ['薰衣草紫', '浅灰紫'],
  'black&red': ['中紫红色', '中紫红色'],
  'light gray': ['浅灰紫', 'Grey Blue'],
  'watermelon red': ['西瓜粉色', '西瓜粉色'],
  'light coffee': ['咖啡色', 'Reddish Brown'],
  leopard: ['复古', 'Mermaid Magic'],
  'fluorescent green': ['荧光色', '荧光色'],
  clear: ['透视', 'Haze Blue'],
  'mint green': ['薄荷绿', '薄荷绿'],
  camouflage: ['桃色', 'Glow Purple'],
  'dark coffee': ['亚麻金', '咖啡棕'],
  'dark red': ['红木色', '红木色'],
  'light yellow': ['姜色', '姜色'],
  'black&blue': ['蓝黑色', '中等水洗蓝'],
  'milk white': ['亮白', '红白色'],
  rainbow: ['燃橙色', '燃橙色'],
  'leopard print': ['热带印花', 'Black Floral'],
  'black&green': ['橄榄绿', '橄榄绿'],
  'black&grey': ['碳灰色', '锈棕色'],
  'black&gold': ['D113古铜金', 'Bronze Green'],
  ivory: ['象牙色', 'Pure White'],
  'deep pink': ['珊瑚色', 'Fuchsia Pink'],
  'red&black': ['红白色', 'Dry Rose'],
  'rose pink': ['枯玫瑰色', '浅粉'],
  'blue&white': ['蓝白色', '蓝白色'],
  'white&blue': ['青碧色', 'Silver Raw White'],
  'sapphire blue': ['水鸭蓝', 'Aegean Blue'],
  'grass green': ['绿松石色', 'Apple Green'],
  'white&black': ['拼色', 'Light Beige'],
  natural: ['自然白', 'Oyster Mushroom'],
  cyan: ['青柠色', '青柠色']
};
